-   name: create users
    become: true
    vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
        password: $6$jZfwycaz$4l7aCeTAA21ONQzEspfs/6NA5biDhXXA.oQ4iERwxImPMdQVIrm2PedNL0dMekpiXpNvdJGp4RWtW0fcip66u1
    user:
        name: "{{ item.nombre }}"
        state: present
        group: "{{ item.grupo }}"
    with_items:
        - { nombre: hual7, grupo: sniper, password: "{{password}}" }
        #- { nombre: claudia, grupo: sniper}